# Vectors, matrices and norms

The notebook demonstrate the computation and use of some important concepts in linear algebra. NumPy is used for the numerical computations.

## Vector norms

The $l_{p}$-norm,of a vector $\boldsymbol{x} \in \mathbb{R}^{n}$ is 

$$
\| \boldsymbol{x} \|_{p} = \left( \sum_{i=1}^{n} |x_{i}|^{p} \right)^{1/p}
$$

Recall that when $p = \infty$, we have have the maxiumum norm:

$$
\| \boldsymbol{x} \|_{\infty} = \max(|x_{1}|, \ldots , |x_{n}|)
$$



NumPy can compute $l_{p}$ norms of vectors. To see how, we first import NumPy and create a random vectors of length 10:

In [1]:
import numpy as np
np.random.seed(2)

x = np.random.rand(10)
print(x)

[ 0.4359949   0.02592623  0.54966248  0.43532239  0.4203678   0.33033482
  0.20464863  0.61927097  0.29965467  0.26682728]


We can now compute a number of $l_{p}$ norms of $\boldsymbol{x}$:

In [2]:
for p in range(1, 5):
    x_norm = np.linalg.norm(x, p)
    print("The l_{} norm of x is: {}".format(p, x_norm))

The l_1 norm of x is: 3.58801017672414
The l_2 norm of x is: 1.2468342486734338
The l_3 norm of x is: 0.901952092265244
The l_4 norm of x is: 0.7790858352598121


For the $l_{\infty}$ norm:

In [3]:
 x_inf = np.linalg.norm(x, np.inf)
print("The max norm of x is: {}".format(x_inf))

The max norm of x is: 0.6192709663506637


## Matrix norms

Norms of matrices can also be computed. The more interesting (and abstract) norms and *operator* norms. These are also known as *induced* norms.

### Operator norms

For an $n \times n$ matrix $\boldsymbol{A}$, the norm of the matrix is a measure of the maximum change in relative length it induces when applied to a vector. If we consider:  

$$
\| \boldsymbol{A}  \boldsymbol{x} \| \le C \| \boldsymbol{x}\| \quad \forall \boldsymbol{x} \in \mathbb{R}^{d},
$$

then the smallest possible $C$ is the norm of $\boldsymbol{A}$. The norm of $\boldsymbol{A}$ is denoted by $\|\boldsymbol{A}\|$:

$$
\| \boldsymbol{A}  \boldsymbol{x} \| \le \| \boldsymbol{A}\| \| \boldsymbol{x}\| \quad \forall \boldsymbol{x} \in \mathbb{R}^{d},
$$

The can be rearranged to provide the ussual definition of a matrix norm:

$$
\| \boldsymbol{A} \| = \max_{\boldsymbol{x} \in \mathbb{R}^{n} \backslash \boldsymbol{0}}
    \frac{\| \boldsymbol{A} \boldsymbol{x}\|}{\|\boldsymbol{x}\| }
$$

To compute actual norms of a matrix, we need to choose how we measure the length of a vector, i.e. which norm to use. If we choose the $l_{2}$-norm, then:

$$
\| \boldsymbol{A} \|_{2} = \max_{\boldsymbol{x} \in \mathbb{R}^{n} \backslash \boldsymbol{0}}
    \frac{\| \boldsymbol{A} \boldsymbol{x}\|_{2}}{\|\boldsymbol{x}\|_{2} }
$$

As discussed in the lectures, some norms are relatively inexpensive to compute for large matrices, and others are expensive. We can again use NumPy to compute some matrix norms. We first create a matrix filled with random numbers:

In [4]:
A = np.random.rand(5, 5)
print(A)

[[ 0.62113383  0.52914209  0.13457995  0.51357812  0.18443987]
 [ 0.78533515  0.85397529  0.49423684  0.84656149  0.07964548]
 [ 0.50524609  0.0652865   0.42812233  0.09653092  0.12715997]
 [ 0.59674531  0.226012    0.10694568  0.22030621  0.34982629]
 [ 0.46778748  0.20174323  0.64040673  0.48306984  0.50523672]]


In [5]:
print("The l_1 norm of A is: {}".format(np.linalg.norm(A, 1)))
print("The l_2 norm of A is: {}".format(np.linalg.norm(A, 2)))
print("The max norm of A is: {}".format(np.linalg.norm(A, np.inf)))

The l_1 norm of A is: 2.9762478642685686
The l_2 norm of A is: 2.1984266817802913
The max norm of A is: 3.0597542402046187


### Vector-like norms

It sometimes convenient to work with matrix norms that are similar to vector norms. A commonly used matrix norm is the Frobenius norm. It is analogous to the $l_{2}$ norm of a vector, as defined by

$$
\|\boldsymbol{A} \|_{F} = \left( \sum_{i}\sum_{i} a_{ij}^{2} \right)^{1/2} 
$$

To compute the Frobenius norm:

In [6]:
A_frobenius = np.linalg.norm(A, 'fro')
print("The Frobenius norm of A is: {}".format(A_frobenius))

The Frobenius norm of A is: 2.347575815854758


## Condition number

The condition number of a matrix is important when working with matrices numerically because is tells us something about how stable algorithms will be with respect to round-off errors, and how fast some iterative techniques will converge. Recall that the condition number $\kappa$ of a matrix $\boldsymbol{A}$ is defined as:

$$
\kappa(\boldsymbol{A}) = \| \boldsymbol{A} \| \|\boldsymbol{A}^{-1}\|
$$

If we use the 2-norm, it was shown that:

$$
\kappa_{2}(\boldsymbol{A}) = \frac{\sqrt{\lambda_{\max}(\boldsymbol{A}^{T}\boldsymbol{A})}}{\sqrt{\lambda_{\max}(\boldsymbol{A}^{T}\boldsymbol{A})}}
$$

### Effect of poor conditioning on errors

It was shown in lectures that when solving $\boldsymbol{A} \boldsymbol{x} = \boldsymbol{b}$, if the condition number of $\boldsymbol{A}$ is large, the small errors in $\boldsymbol{b}$ can manifest themselves as large errors in the solution  $\boldsymbol{x}$. We explor this now for the notoriously ill-conditioned *Hilbert matrix*. Entries of the Hilbert matrix $\boldsymbol{H}$ are given by

$$
H_{ij} = \frac{1}{i+j-1}
$$

We can use a SciPy function to create a $n \times n$ Hilbert matrix:

In [7]:
import scipy.linalg as la

H = la.hilbert(6)
print(H)
print("Condition number is: {}".format(np.linalg.cond(A, 2)))

[[ 1.          0.5         0.33333333  0.25        0.2         0.16666667]
 [ 0.5         0.33333333  0.25        0.2         0.16666667  0.14285714]
 [ 0.33333333  0.25        0.2         0.16666667  0.14285714  0.125     ]
 [ 0.25        0.2         0.16666667  0.14285714  0.125       0.11111111]
 [ 0.2         0.16666667  0.14285714  0.125       0.11111111  0.1       ]
 [ 0.16666667  0.14285714  0.125       0.11111111  0.1         0.09090909]]
Condition number is: 127.37148321616641


Even for this small Hilbert matrix, the condition number is large.

We now experiment with solving $\boldsymbol{A} (\boldsymbol{x}+ \delta \boldsymbol{x}) = \boldsymbol{b} + \delta \boldsymbol{b}$, and compare the error $\|\delta{\boldsymbol{x}}\| / \|\boldsymbol{x}\|$ to $\|\delta{\boldsymbol{b}}\| / \|\boldsymbol{b}\|$. We will presume that the NumPy linear solvers can cope with the exact system $\boldsymbol{A}\boldsymbol{x} =\boldsymbol{b}$.

We first construct $\boldsymbol{b}$, $\delta\boldsymbol{b}$ and $\boldsymbol{b} + \delta\boldsymbol{b}$:

In [8]:
b       = np.ones(H.shape[0])
b_delta = 1.0e-6*np.random.rand(H.shape[0])

# Perturbed RHS
b1  = b + b_delta

We now solve for $\boldsymbol{A} \boldsymbol{x}=  \boldsymbol{b}$ and $\boldsymbol{A} (\boldsymbol{x}+ \delta \boldsymbol{x}) = \boldsymbol{b} + \delta \boldsymbol{b}$:

In [9]:
x  = np.linalg.solve(H, b)
x1 = np.linalg.solve(H, b1)

We now compare $\|\delta{\boldsymbol{x}}\| / \|\boldsymbol{x}\|$ and $\|\delta{\boldsymbol{b}}\| / \|\boldsymbol{b}\|$:

In [10]:
error_x = np.linalg.norm(x - x1, 2)/np.linalg.norm(x, 2)
error_b = np.linalg.norm(b_delta, 2)/np.linalg.norm(b, 2)
print("Relative in x and b: {}, {}".format(error_x, error_b))

Relative in x and b: 0.0002460625680546956, 6.536697245233218e-07


Even for this small Hilbert matrix, a small error in $\boldsymbol{b}$  leads to a much larger error in $\boldsymbol{x}$. This will get worse with problem size.  We'll now put the test in side a loop to test larger matrices:

In [11]:
for n in (20, 100, 1000):
    H = la.hilbert(n)
    print("- For {} x {} matrix, the condition number is: {}".format(n, n, np.linalg.cond(H, 2)))
    
    b       = np.ones(H.shape[0])
    b_delta = 1.0e-6*np.random.rand(H.shape[0])
    b1  = b + b_delta
    
    x  = np.linalg.solve(H, b)
    x1 = np.linalg.solve(H, b1)
    
    error_x = np.linalg.norm(x - x1, 2)/np.linalg.norm(x, 2)
    error_b = np.linalg.norm(b_delta, 2)/np.linalg.norm(b, 2)
    print("   Relative in x and b: {}, {}".format(error_x, error_b))

- For 20 x 20 matrix, the condition number is: 8.785814386829997e+17
   Relative in x and b: 124.52695173605895, 6.170628724642186e-07
- For 100 x 100 matrix, the condition number is: 1.3290065782827812e+20
   Relative in x and b: 721.8193247240508, 5.285972913277156e-07
- For 1000 x 1000 matrix, the condition number is: 4.4921327959498726e+20
   Relative in x and b: 43.12207284345131, 5.716480316215122e-07


### Condition number versus determinant

It was discussed in lecture that the condition number of a matrix and its determinant are not necessarily related. Some small examples were presented. Here we consider some larger problems.

We consider an $n \times n$ upper triangular matrix filled with two, and one on the diagonal:

$$
\boldsymbol{A} = \begin{bmatrix} 
1 & 2 & \ldots & 2 
\\
  & 1 & \ddots & \vdots 
\\
  &   & \ddots & 2
\\
   &  &        & 1
\end{bmatrix}
$$

This matrix has a determinant of one, and a condition number that grows with $n$. We can explore this with NumPy for increasing $n$.

In [12]:
def test_matrix(n):
    A = np.zeros((n, n))
    A[np.triu_indices(n)] = 2.0
    np.fill_diagonal(A, 1.0)
    return A

for n in (2, 10, 100, 500):
    A = test_matrix(n)
    print("- Matrix size: {} x {}".format(n, n))
    print("   * l_2 condition number is: {}".format(np.linalg.cond(A, 2)))
    print("   * determinant is: {}".format(np.linalg.det(A)))

- Matrix size: 2 x 2
   * l_2 condition number is: 5.82842712474619
   * determinant is: 1.0
- Matrix size: 10 x 10
   * l_2 condition number is: 161.4476387975885
   * determinant is: 1.0
- Matrix size: 100 x 100
   * l_2 condition number is: 16210.722720219756
   * determinant is: 1.0
- Matrix size: 500 x 500
   * l_2 condition number is: 405284.0679028457
   * determinant is: 1.0
